// Alert
export const SHOW_PROJECT_ALERT = 'SHOW_PROJECT_ALERT'
export const SHOW_TASK_ALERT = 'SHOW_TASK_ALERT'
export const SHOW_ALERT = 'SHOW_ALERT'
export const HIDEE_ALERT = 'HIDEE_ALERT'

// Auth
export const SUCCESS_REGISTRATION = 'SUCCESS_REGISTRATION'
export const ERROR_REGISTRATION = 'ERROR_REGISTRATION'
export const SUCCESS_LOGIN = 'SUCCESS_LOGIN'
export const ERROR_LOGIN = 'ERROR_LOGIN'
export const GET_USER = 'GET_USER'
export const LOGOUT = 'LOGOUT'

// Project
export const CREATE_NEWPROJECT = 'CREATE_NEWPROJECT'
export const ERROR_NEWPROJECT = 'ERROR_NEWPROJECT'
export const GET_PROJECTS = 'GET_PROJECTS'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const SELECT_PROJECT = 'SELECT_PROJECT'

// Task
export const CREATE_TASK = 'CREATE_TASK'
export const ERROR_TASK = 'ERROR_TASK'
export const GET_TASKS = 'GET_TASKS'
export const UPDATE_TASK = 'UPDATE_TASK'
export const SELECT_TASK = 'SELECT_TASK'
export const DELETE_TASK = 'DELETE_TASK'